### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [DanilaEremenko/EDLargeInteger-#1]
1. Нужно выполнить проверку строки, переданной в конструктор, прямо в конструкторе. (В новой версии Вы это как-то реализовали, но можно намного проще. Посмотрите про `Character.isDigit`).
1. Сделайте конструктор из `long`.
1. Переделайте класс таким образом, чтобы хранить значение не в строке, а в наборе `int` (`int[]` или `ArrayList<Integer>`).
1. Все операции над числами, которые у Вас возвращают число в виде строки, должны возвращать объект Вашего класса "большое число".
1. Избавьтесь от дублирования кода.
1. Реализуйте деление для делителя любой длины.
1. Вместо `max`, `min` и `equal` реализуйте интерфейс `Comparable` и соответственно его метод `compare`.
1. Переопределите методы `equals`, `hashCode` и `toString`.

**Comment by maximpetrov** [comment]
1. Переделайте проверку правильности числа в конструкторе.
1. Перенесите удаление начальных нулей в конструктор.
1. Постарайтесь убрать создание временных `ArrayList`ов для аргументов в арифметических операциях и при сравнении.
1. В методе `compareTo` можно сразу возвращать результат, а не сохранять его во временную переменную.
1. Метод `delete` должен быть приватным.
1. Сомневаюсь, что метод `size` нужен. Какой в нём смысл для большого целого числа?
1. Метод `ArraytoString` можно сделать статическим. Методы `delzero` и `toEDLargeInteger` в текущей реализации тоже.
1. Вместо метода `toEDLargeInteger` лучше сделать приватный конструктор из `ArrayList`, чтобы избежать лишнего перевода обратно из строки.
1. Вставлять в начало `ArrayList` не эффективно. Лучше добавляйте в конец, а потом переверните или задайте размер сразу и задавайте элементы по нужным индексам вместо добавления.

**Comment by maximpetrov** [comment]
1. Проверка правильности стала чуть лучше, но сделайте её всё-таки без вспомогательных массивов с помощью `isDigit`. Кроме того, проверку можно совместить с переводом в `ArrayList`.
1. Лучше сначала определить количество начальных нулей, а потом один раз сделать `substring`, чем использовать `StringBuilder`.
1. При переводе `arrayList` обратно в строку как раз стоит использовать `StringBuilder`.
1. Что у Вас будет, если число равно 0 (если создать его из строки "0" или аналогичного `ArrayList`)?
1. В сложении и вычитании Вы меняете `ArrayList`ы внутри операндов, а этого делать не стоит. Там вообще можно обойтись без подгона под одну длину.
1. Зачем [здесь](https://github.com/DanilaEremenko/EDLargeInteger-/blob/3b06e9ac22d69d30c7270453ce0b5bf22d52d183/src/EDLargeInteger.java#L82-L90) `if`?
1. Пункт 9 из прошлого набора замечаний всё ещё актуален (он касается реализации умножения).

**Comment by DanilaEremenko** [comment]
@maximpetrov 
1)Проверка правильности переделана через isDigit и совмещена с переводом в ArrayList
2)Переделана обрезка начальных нулей(сначала определяется количество, а потом используется substring)
4)Добавлены тесты с числами созданными из строки "0".
5)Сложение и вычитание переделаны.Подгон под одну длину больше не используется
6)Ненужный if убран
7)Вставки в начало больше нет

**Comment by maximpetrov** [comment]
1. Для переворота результата не нужно прибегать к нескольким преобразованиям туда-обратно. Достаточно использовать `Collections.reverse()`
1. Конструктор из `ArrayList` у Вас копирует только ссылку на передаваемый `ArrayList`. Если Вам нужен такой публичный конструктор, то нужно скопировать не ссылку, а содержимое. Второй вариант - сделать конструктор приватным и аккуратно его использовать.
1. [Здесь](https://github.com/DanilaEremenko/EDLargeInteger/blob/master/src/EDLargeInteger.java#L232) можно не создавать новый объект класса для делимого, а использовать объект класса, на котором вызван метод.
1. Метод `delzero` следовало бы сделать статическим либо убрать аргумент. Кроме того, он вообще не нужен. Во-первых, удаление нулей уже есть в конструкторе из строки, который вызывается в конце этого метода. Во-вторых, объект класса вообще не может содержать начальных нулей, потому что уже был когда-то создан с помощью конструктора, который убирает начальные нули (это ещё одна причина сделать конструктор из `ArrayList` приватным, чтобы пользователь Вашего класса не мог с его помощью создать невалидный объект с начальными нулями).

**Comment by DanilaEremenko** [comment]
@maximpetrov 
1) Для переворота используется Collections.reverse()
2) Конструктор из ArrayList теперь копирует не ссылку,а содержимое
3) Пункт исправлен
4) Ненужный метод delzero убран

**Comment by maximpetrov** [comment]
1. Раз Вы конструктор сделали приватным, то скорее всего Вам копировать содержимое как раз нет необходимости. А если копируете, то используйте более эффективный метод `addAll`.
1. В прошлый раз как-то не заметил, поэтому сейчас спрошу. Зачем [здесь](https://github.com/DanilaEremenko/EDLargeInteger/blob/master/src/EDLargeInteger.java#L242) перевод в строку и обратно?

**Comment by DanilaEremenko** [comment]
@maximpetrov 
1) [Исправил](https://github.com/DanilaEremenko/EDLargeInteger/blob/master/src/EDLargeInteger.java#L40)
2) Сам не знаю, [исправил](https://github.com/DanilaEremenko/EDLargeInteger/blob/master/src/EDLargeInteger.java#L239)
